apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: voting-app
spec:
  containers:
    - name: result-app
      image: sanket01/voting-app-result-app
      ports:
        - containerPort: 80